### ISSUE TITLE
Extract Tables Metadata from Glue Catalog

### ISSUE THREAD

**Issue by rubenssoto** [dataframehq/whale#46]
Hello Guys,

You have a great project here.

All my tables are cataloged with Glue Data Catalog, it will be great if whale could have a connector.

Thank you

**Comment by rsyi** [comment]
Absolutely can get on this. Thanks, Ruben!

**Comment by rsyi** [comment]
Hey @rubenssoto! I've added Glue support in, and merged the change into the latest release. If you're using brew, run `brew upgrade whale`, and it should work. The syntax is as follows:

```
---
name: whatever-you-want
metadata_source: Glue
```

(or alternatively, just run through the `wh init` process again)
There's no options for specifying credential locations yet -- I figured I'd just get something barebones running first. Let me know if you need any additional functionality on that end.
