### ISSUE TITLE
Add better messaging for when there are no tables in a warehouse.

### ISSUE THREAD

**Issue by rsyi** [dataframehq/whale#52]
Currently, when no tables are detected, whale throws an error 

```
FileNotFoundError: [Errno 2] No such file or directory: '~/.whale/manifests/tmp_manifest.txt'
```

The function to change is `copy_manifest` in `pipelines/whale/utils/__init__.py`, which should actually check that the file exists before attempting to copy it. See the `transfer_manifest` function, right above it, for how this might look.

**Comment by beebzz** [comment]
Hey Robert! Not sure if this PR is limited to folks at Dataframe/Whale (found it on a whim) but if not then I'd be happy to take of it for you!

**Comment by rsyi** [comment]
No not at all! Nothing is limited to us, unless it's been assigned. I'll assign you to it! 

Also, we have a channel ("#contributing") in our slack community where I'll be posting these sorts of reasonable "good first issue" issues. Feel free to join if you want to take more of these.
