### ISSUE TITLE
Add docs for contributors.

### ISSUE THREAD

**Issue by rsyi** [dataframehq/whale#56]
Currently, there are no best practices for how to test the stack, best practices for contribution, etc. etc.

**Comment by Victoriapm** [comment]
Hey, I could add a contributing.md file with the instructions on how to create a pull request and work on issues. 
Let me know what you think

**Comment by rsyi** [comment]
Go for it! In the end, I'll probably have to add a bit of stuff that's just in my brain right now (a QA checklist, e.g.), but I can work off your contribution.

Btw, we have a channel (#contributors) in our slack community where I'll post good first issues to familiarize yourself with the codebase + solicit help. Check it out if you're interested in helping out more in the future :)

**Comment by Victoriapm** [comment]
I just made the pull request, probably a lot to improve with the stuff you have in mind but should be a good start with some basic guidelines. Let me know what you think, I’m open to suggestions. 

I'm signing to the slack channel, will definitely have an eye on that channel.

**Comment by rsyi** [comment]
Great work, @Victoriapm! Merged, and will manually update nits :)
