### ISSUE TITLE
Add roadmap.

### ISSUE THREAD

**Issue by rsyi** [dataframehq/whale#57]
For visibility. I'll add this in later, but if you have a feature request, either post it here, in slack, or **make an issue** and I'll add it to the roadmap!

Possible features:
* Data profiling
* Additional bigquery metadata (e.g. tags)
* Cloud Spanner support

**Comment by biomunky** [comment]
Would be interested in adding spanner + pulling metadata e.g. tags, from GCP for BQ & Spanner(?)

**Comment by rsyi** [comment]
Oh huh. We can absolutely add that. Are you on spanner? 
Yeah there's a whole wealth of additional information that we should be pulling from Bigquery & Google's APIs. Happy to add that in.

**Comment by thinhha** [comment]
+1 for pulling [BQ Tags from Data Catalog](https://cloud.google.com/data-catalog/docs/concepts/overview#tags)

would also be great if we could annotate the columns with [policy tags](https://cloud.google.com/bigquery/docs/column-level-security-intro) directly in the md to indicate whether it contains PII or sensitive data.

**Comment by biomunky** [comment]
@rsyi I'm using spanner and figured as you've got BQ it wouldn't do any harm to add it.

**Comment by rsyi** [comment]
@thinhha Added to the roadmap. :)
And yeah @biomunky for sure. I'll actually just open an issue for spanner.

**Comment by rsyi** [comment]
@thinhha can you open separate issues for both pulling down BQ tags and upserting policy tags?

Pulling BQ tags should be super straightforward. But the upsertion less so. There's a ton of ways I can think of to do it, but I think choosing a nice UX pattern is going to be a bit tricky. Let me have a think, and I'll come back with some options. :)
