### ISSUE TITLE
chore: cargo-ci should only run when cli/ is modified

### ISSUE THREAD

**Issue by biomunky** [dataframehq/whale#58]
The Cargo-CI action currently runs when any file in the repo is modified, it would probably be better for it to run only when files under `cli/` are modified.

Workflow here: https://github.com/dataframehq/whale/blob/master/.github/workflows/cargo-ci.yml
Update based on https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

**Comment by rsyi** [comment]
Very good point. Same thing for python.

**Comment by biomunky** [comment]
Was just about to update for python, since my code just failed because of it.

**Comment by rsyi** [comment]
Thanks for this @biomunky!
