### ISSUE TITLE
Google Cloud Spanner support

### ISSUE THREAD

**Issue by rsyi** [dataframehq/whale#68]
This will involve:
1. Writing a new Extractor that runs a query that scrapes metadata from Spanner.
2. Writing logic into `pipelines/utils/task_wrappers.py` and `pipelines/utils/extractor_wrappers.py` to run the above Extractor when `wh.pull` is called.

We'll also later have to add this as an option to the `wh init` workflow in rust, but the library will function without that, so it's less priority for now.

**Comment by rsyi** [comment]
Some initial work done here using `information_schema` (but missing types, unfortunately): https://github.com/dataframehq/whale/pull/69.

@manuelzander is currently working on this here, using `ddlparse` on `create table` statements to get the type (better):
https://github.com/dataframehq/whale/compare/master...manuelzander:master

**Comment by manuelzander** [comment]
We could either make `ddlparse` compatible with all Spanner data types (I've started with https://github.com/shinichi-takii/ddlparse/pull/62, but also need to add `BYTES`, support for `ARRAY`, nested arrays etc.) I guess the proper way of doing this would be adding `spanner` to the `source_database` config.
OR we write or own parser. 
Any other ideas?

**Comment by rsyi** [comment]
Hm. Seems like we could also just add a helper function that parses the `DdlParse.parse` result. I'll give this a quick try and open a PR for you to check. (What do you think?)
A little hacky, but avoids relying on the PR or having to crack open the parsing logic.

**Comment by rsyi** [comment]
(Deleted my comment, as I dove into the code base a bit and figured out what's possible and not possible 😅 )

Looks like we can also just import the logic of `to_bigquery_fields` in and implement it ourselves. I gave this a quick shot and opened a PR on your fork lol. What do you think? (feel free to reject, only spent like 30 minutes on this)

**Comment by manuelzander** [comment]
@rsyi See https://github.com/manuelzander/whale/pull/1#issuecomment-719561884 😊
