### ISSUE TITLE
whale Installation fails in Ubuntu 20.04

### ISSUE THREAD

**Issue by Fugit185** [dataframehq/whale#87]
My enironment is

>Ubuntu 20.04

I run git packet installation command

> git clone https://github.com/dataframehq/whale.git

Then I go to whale folder and run following command

> linttu@linttu-VirtualBox:~/Desktop/whale$ make && make install

The result and error is

>cargo build --release --manifest-path cli/Cargo.toml
>make: cargo: Command not found
>make: *** [Makefile:10: rust] Error 127

**Comment by biomunky** [comment]
[cargo](https://doc.rust-lang.org/cargo/) is the rust package manager, try installing rust/cargo via [rustup](https://rustup.rs/)

**Comment by rsyi** [comment]
^ Exactly what biomunky said. Good callout. Let me know if that helps, @Fugit185!

**Comment by Fugit185** [comment]
Thanks, I installed cargo, and now it continues installation, so that part is working!

But then installation stops and I get follwowing error. I moved this to conda virtual environment, that is why command line starts with (whale)   
 
```
(whale) linttu@linttu-VirtualBox:~/Desktop/whale/whale$ make && make install --verbose
cargo build --release --manifest-path cli/Cargo.toml
   Compiling libc v0.2.80
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: could not compile `libc`.

To learn more, run the command again with --verbose.
make: *** [Makefile:10: rust] Error 101
```
