### ISSUE TITLE
Latest PyPI release does not contain any code

### ISSUE THREAD

**Issue by jwodder** [dataframehq/whale#97]
The latest release (1.2.0) of whale-pipelines on PyPI does not contain any of the project's code.  You can verify this by [downloading the assets](https://pypi.org/project/whale-pipelines/1.2.0/#files) and listing their contents with `tar ztf whale-pipelines-1.2.0.tar.gz` and `zipinfo whale_pipelines-1.2.0-py2.py3-none-any.whl`.

I suspect that the cause of this problem is that the files were built by running `python3 pipelines/setup.py ...` from the root of the repository.  `setup.py` should instead be run from the directory in which `setup.py` is located (or, even better, use [build](https://github.com/pypa/build), which takes care of the change in directory for you).

Also, while I'm here, I noticed that, when your wheel is built correctly, it contains the `tests/` directory at the top level.  This is inadvisable; [see here](https://jwodder.github.io/kbits/posts/pypkg-mistakes/#top-level-tests-directory-in-wheel) for why and how to fix it.

**Comment by rsyi** [comment]
@jwodder Ah you're right. That's odd. I'll fix that immediately. Thanks for pointing it out!

Regarding your second point -- this is terrible! I've been storing `tests/` as a subdirectory for years without exclusion. For this also, thanks for pointing it out. I shudder to think how much cruft I've added to the `tests` library over the years...
Option 2 seems like it'll work without breaking anything else (`packages=find_packages(exclude=["tests", "tests.*"])`). If you're feeling up to it, feel free to open a PR, and I can merge it. :)

**Comment by rsyi** [comment]
In case anyone else is curious re: the empty pypi library, [here's the official documentation on the matter](https://docs.python.org/3/install/#platform-variations), and here's some evidence of the problem happening:

Running `python pipelines/setup.py sdist bdist_wheel --universal` from the project root (notice the file size):
![image](https://user-images.githubusercontent.com/28232885/99918829-67207e80-2cce-11eb-9f2b-2c936a637a8c.png)

Running `python setup.py sdist bdist_wheel --universal` from the `pipelines` directory:
![image](https://user-images.githubusercontent.com/28232885/99918867-ae0e7400-2cce-11eb-8b18-74ba08f9b6a4.png)

**Comment by rsyi** [comment]
Alright. @jwodder this is sort of good to go (you'll have to explicitly define the version since it's a release candidate `pip install whale-pipelines=1.2.1rc0`), but I've realized my `install_requires` is also pretty out of date, so it'll install but be missing some essential libraries. I'll fix that later and then push a new release
